version: '3.4'

services:
  reacttsboilerplate:
    image: reacttsboilerplate
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      env_file: .env
      NODE_ENV: production
    ports:
      - 3000:3000
