name: Run Jest Tests

on:
  pull_request: branches:[main]

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with: node-version:12
      - run: npm ci
      - run: npm test
      - run: npm run build
